### ISSUE TITLE
更新了最新版本后，修改.v文件会再FPGA tool里会出现两个文件

### ISSUE THREAD

**Issue by qgzln** [Bestduan/Digital-IDE#26]
![image](https://user-images.githubusercontent.com/47837258/133209719-cce68af3-55f3-409a-ace1-f9fe7a567176.png)
如图，我将UART_Decode这个文件改名字为UART_Decode_Debug，结果修改前的文件名字也保存下来了，实际上文件夹里没有UART_Decode这个文件了

**Comment by Bestduan** [comment]
将System_Parmeter_Debug所在文件重新保存一下即可，这时System_Parmeter_Debug就会找不到UART_Decode_Debug这个模块而报红了。

**Comment by Bestduan** [comment]
新版本已修复该问题。
