### ISSUE TITLE
Extension activation failed

### ISSUE THREAD

**Issue by votechok** [Bestduan/Digital-IDE#35]
Extension does not work in this project:
![image](https://user-images.githubusercontent.com/98825020/151983799-9b59eacf-6085-4e99-9428-c2e2f00b244e.png)
In other projects, the extension works fine

**Comment by Bestduan** [comment]
I found the problem a few days ago, but I could not find the source of the problem, because there was no error before vscode updated. Now I am changing a new resolution scheme of parsing to solve the problem in the next extension version.

**Comment by Bestduan** [comment]
It has been fixed in new version , please check again to see if it works.
