### ISSUE TITLE
Test Bench 导致溢出

### ISSUE THREAD

**Issue by bqsgwys** [Bestduan/Digital-IDE#38]
项目文件结构如图
![image](https://user-images.githubusercontent.com/7232214/155057184-a920d249-8275-4c53-9ca1-6ee148996ec3.png)
刚刚写一点testbench的时钟
![image](https://user-images.githubusercontent.com/7232214/155056974-17dd63ec-06b9-4517-a764-23482d75868b.png)
爆栈 然后 file部分不显示

**Comment by Bestduan** [comment]
进行simulate时是右击选择simulate还是在FPGA option中选择的simulate？
不过按理说都不会导致这种情况，我到现在还没遇到过- _ -||

**Comment by bqsgwys** [comment]
没有simulate，保存就爆栈了

**Comment by Bestduan** [comment]
爆栈的问题经常出现吗，还是说每次保存文件就会出现？按理说估计不是我的扩展的问题

**Comment by bqsgwys** [comment]
![image](https://user-images.githubusercontent.com/7232214/155071053-52d3da24-9c85-4039-95ac-d37923d5a9d9.png)
感觉上是file在遍历的时候爆的栈

**Comment by bqsgwys** [comment]
sim下没有模组就没问题

**Comment by bqsgwys** [comment]
找到问题了
![image](https://user-images.githubusercontent.com/7232214/155071190-e1d46c7a-7cc5-4fe7-8306-8beb625782f1.png)

sim的模组不能叫做sim，要不就与父级同名（我猜你是拿字符匹配做的搜索

**Comment by Bestduan** [comment]
确实，vscode中的树结构使用的是递归，一直是sim的话会一直递归下去导致爆栈，确实没想到。
