### ISSUE TITLE
gtkwave 在 vscode 不能打开

### ISSUE THREAD

**Issue by hhucchenyixiao** [Bestduan/Digital-IDE#42]
simulation后会报一个警告，然后gtkwave不弹出
![image](https://user-images.githubusercontent.com/96377023/165722969-e8f36bae-4b0a-4f5e-9b54-1730fce0f331.png)

只能手动打开
![image](https://user-images.githubusercontent.com/96377023/165724998-32894237-98cd-4856-b474-59beacce03cd.png)

**Comment by Bestduan** [comment]
你在setting中是否设置了TOOL.gtkwave.install.path

**Comment by Bestduan** [comment]
或者里面有空格忘记删了？

**Comment by Bestduan** [comment]
已记录为已知bug，今晚我回去测试一下

**Comment by hhucchenyixiao** [comment]
系统变量里面都加了

然后vscode里面路径填或者不填我试了效果都一样







------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Bestduan/Digital-IDE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月28日(星期四) 晚上6:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Bestduan/Digital-IDE] gtkwave 在 vscode 不能打开 (Issue #42)





 
你在setting中是否设置了TOOL.gtkwave.install.path

**Comment by Bestduan** [comment]
和设置没关系，是nodejs里match方法更新了

**Comment by Bestduan** [comment]
新版本已经修复

**Comment by hhucchenyixiao** [comment]
多谢了，那我关闭问题了
