### ISSUE TITLE
模块层次树失效

### ISSUE THREAD

**Issue by xlsjdjdk** [Bestduan/Digital-IDE#45]
文件栏里中，层次树的子模块及其分支不再显示，如图：
![image](https://user-images.githubusercontent.com/52185645/166909433-683a8cce-4416-4235-b254-3a5536efee99.png)
文件位置如图，所有文件都在工作区文件夹下：
![image](https://user-images.githubusercontent.com/52185645/166909516-581586fb-2193-4a4e-b879-b6f936a2f497.png)

**Comment by Bestduan** [comment]
这个你重新保存一下就好了，或者刷新一下

**Comment by Bestduan** [comment]
建议加QQ群：932987873 这样可以及时回复你的问题
