### ISSUE TITLE
希望支持括号辅助

### ISSUE THREAD

**Issue by joson1** [Bestduan/Digital-IDE#49]
效果类似于：

![image](https://user-images.githubusercontent.com/29445770/178883892-c4c9ffb4-0829-4447-83ea-5c5d829b5bf4.png)

光标停在begin处会自动框起来end，反过来也是可以的

**Comment by Bestduan** [comment]
![image](https://user-images.githubusercontent.com/38045864/178889831-c04cafd0-fea4-4e15-bce1-29006786e45e.png)
插件是支持框的，但从end处括起来应该是vscode本身不支持

**Comment by joson1** [comment]
我提的插件是这款 https://marketplace.visualstudio.com/items?itemName=mshr-h.VerilogHDL
让vscode将begin end 当 { } 来处理，还支持colourful brackets，就是不通层级的括号 颜色不同
![image](https://user-images.githubusercontent.com/29445770/180648651-a596beea-a809-452b-b370-22a5530a8092.png)
![image](https://user-images.githubusercontent.com/29445770/180648665-478372bd-0d05-4364-bf5c-1e42ed9a4db9.png)

**Comment by joson1** [comment]
![image](https://user-images.githubusercontent.com/29445770/180648797-32a6054f-52b5-4dc4-9043-04c03b0f5c6b.png)
这个插件目前已经集成在最新版的VS code中了

**Comment by Bestduan** [comment]
好的，我试一下

**Comment by Bestduan** [comment]
新版本0.2.5已经修复该问题，请check out一下。

**Comment by joson1** [comment]
太赞了！
