### ISSUE TITLE
网站bestduan.github.io失效了？

### ISSUE THREAD

**Issue by TurnOffNOD** [Bestduan/Digital-IDE#52]
网站bestduan.github.io是作者自己停了还是故障了？

**Comment by Bestduan** [comment]
是的，我已经关闭我的github博客，插件内容转到知乎下了

**Comment by TurnOffNOD** [comment]
> 是的，我已经关闭我的github博客，插件内容转到知乎下了

多谢回复。

**Comment by TurnOffNOD** [comment]
> 是的，我已经关闭我的github博客，插件内容转到知乎下了

多谢回复。
